name: Tower_of_trails
version: '0.1'
main: ToT.Main
api-version: 1.19

commands:
  progress:
    description: progress
    usage: /<command>
  queststatus:
    description: queststatus
    usage: /<command>
  startquest:
    description: queststatus
    usage: /<command>
  quests:
    description: queststatus
    usage: /<command>
  reset:
    description: Reset.
    usage: /<command>
  jreload:
    description: jreload.
    usage: /<command>